[project]
name = "{{ cookiecutter.project_slug }}"

[tool.pixi.workspace]
channels = ['conda-forge', 'bioconda']
platforms = ['linux-64', 'osx-arm64']

[dependencies]
python = "{{ cookiecutter.python }}"
snakemake = ">=8"
seaborn = ">=0.13"
pandas = ">=2"
deeptools = ">=3.5.5"
graphviz = "8.1.0"
rich-click = ">=1.8"
bedtools = ">=2.31"
pip = "*"

[pypi-dependencies]
snakemake-executor-plugin-cluster-generic = ">=1.0.9"
snakemake-executor-plugin-slurm = ">=1.8.0"
