[workspace]
name = "{{ cookiecutter.project_slug }}"
channels = ['conda-forge', 'bioconda']
platforms = ['linux-64', 'osx-arm64']

[dependencies]
python = "={{ cookiecutter.python }}"
nextflow = ">=25.0.0"
seaborn = ">=0.13"
pandas = ">=2"
deeptools = ">=3.5.5"
rich-click = ">=1.8"
bedtools = ">=2.31"
pip = "*"

[pypi-dependencies]
