name: cutting_cookies

on:
  push:
  pull_request:

jobs:
  test_projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [bioproject, nfproject, pyproject]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: install_cookiecutter
        run: |
          pip install cookiecutter ruff
      - name: ${ matrix.projects }
        run: |
          cookiecutter --directory ${{ matrix.projects }} . --no-input
      - name: lint
        run:
          ruff check another_project
      - name: pixi_env
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          cache: false
          working-directory: another_project
      - name: pixi_run
        if: matrix.projects == 'pyproject' || matrix.projects == 'bioproject'
        working-directory: another_project
        env:
          PIXI_CMD: ${{ matrix.projects == 'bioproject' && 'python run.py' || 'python --version' }}
        run: |
          pixi run ${{ env.PIXI_CMD }}
