name: cutting_cookies

on:
  push:
  pull_request:

jobs:
  test_projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [bioproject, nfproject, pyproject]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: install_cookiecutter
        run: |
          pip install cookiecutter
      - name: ${ matrix.projects }
        run: |
          cookiecutter --directory ${{ matrix.projects }} . --no-input
      - name: run_bioproject
        if: matrix.projects == 'bioproject'
        run: |
          python another_project/run.py
          test -f another_project/Results_another_project/README.txt || (echo "README.txt not created." && exit 1)
          
